flask:
  - name: SECRET_KEY
    required: True

server:
  - name: UPLOAD_FOLDER
    required: False
    default: 'uploads/'
  - name: VIEW_DIRECTORIES
    required: False
    default: True
  - name: UPLOAD_CHUNK_SIZE
    required: False
    default: 64 * 1024
  - name: DOMAIN_NAME
    required: False
    default: 'example.com'
  - name: PORT
    required: False
    default: 8080
  - name: UPLOAD_SUBDOMAIN
    required: False
    default: 'upload'
  - name: DELETE_SUBDOMAIN
    required: False
    default: 'upload'
  - name: VIEW_SUBDOMAIN
    required: False
    default: 'static'
  - name: STYLING_PATH
    required: False
    default: '$_styling'
  - name: STYLING_FOLDER
    required: False
    default: 'styling'

users: